version: "3.4"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/traefik:/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=tecnologia@be.capital"
      - "--certificatesresolvers.myresolver.acme.storage=/traefik/acme.json"

  api:
    build: 
      context: .
    image: reisalbuquerque/becapital_invest_api:latest
    command: npm run dev
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORE_MYSQL_USER=${CORE_MYSQL_USER}
      - CORE_MYSQL_PASSWORD=${CORE_MYSQL_PASSWORD}
      - CORE_MYSQL_DATABASE=${CORE_MYSQL_DATABASE}
      - CORE_MYSQL_HOST=db
      - CORE_MYSQL_PORT=3306
      - CORE_MYSQL_POOL_MIN=1
      - CORE_MYSQL_POOL_MAX=5
      - PREFIX_PATH=/core/api/v1
      - JWT_PRIVATE_KEY=abc123
      - SENDGRID_API_KEY=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
      - SENDGRID_SIGNUP_TEMPLATE_ID=d-4dcd0895274045c8b4694f84c90bacd0
    depends_on: 
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`api.be.capital`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      
  db:
    image: mysql:5.7
    command:
      - --default-authentication-plugin=mysql_native_password 
      - --innodb-use-native-aio=0
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${CORE_MYSQL_PASSWORD}
      - CORE_MYSQL_DATABASE=${CORE_MYSQL_DATABASE}
    ports:
      - 3307:3306